name: Transfer Minecraft Docker Compose Files
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "docker/mc-1.6.4, docker/mc-bta, docker/mc-latest"
          target: /home/minecraft 
